for auto run observer
oceanbase/miniob pull request #121
Opened 2022-11-14 07:18 UTC by FrankXMX

可以不进入容器里面运行observer和obclient。

====================
$ sudo docker build . -t oceanbase/miniob

$ sudo docker ps
CONTAINER ID   IMAGE              COMMAND                  CREATED         STATUS         PORTS     NAMES
f083234ff32a   oceanbase/miniob   "observer -f /usr/lo…"   4 minutes ago   Up 4 minutes             miniob

$ sudo docker run -d --name miniob --privileged oceanbase/miniob
25495069620d57d7700e15c42d0672a1f6b27e1a27cc2932e12af154a328dcf5

$ sudo docker exec -it miniob obclient
miniob > show tables;
No table
miniob >

2022-11-14 07:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/miniob?pullRequest=121) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/miniob?pullRequest=121) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/miniob?pullRequest=121) it.</sub>

2022-11-14 12:20 UTC, hnwyllmm requested changes

2022-11-14 12:20 UTC, hnwyllmm commented on Dockerfile
> +CMD [ "observer", "-f", "/usr/local/etc/observer.ini" ]
直接在容器中启动一个observer进程，会不方便调试。比如我进入容器后，想要再启动一个自己的observer进程做测试，会失败，因为端口被占用。

2022-11-15 01:13 UTC, FrankXMX commented on Dockerfile
> +CMD [ "observer", "-f", "/usr/local/etc/observer.ini" ]
了解了，我原来理解是要弄一个像OceanBase那样的直接可运行的数据库实例容器，如果容器的目的是调试那确实没有比较直接启动。

2023-03-11 13:58 UTC, closed without merging