Fix problem that record may overflow the page
oceanbase/miniob pull request #232
Opened 2023-08-10 11:23 UTC by JugendTraum

### What problem were solved in this pull request?

Issue Number: close #226

Problem:
记录管理部分中page_header_中record_capacity初始化有误，需要进行修正
由于record_capacity的计算并没有考虑8字节对齐，计算的是不对齐时页面下容纳的最大记录量。
但第一条记录偏移量first_record_offset需要8字节对齐，使得最后一条记录的数据可能会溢出页面。
### What is changed and how it works?
如果溢出页面，则减少record_capacity数值
同时去掉了部分冗余或含义不清的函数，修改了上取整的计算表达式
完善了记录管理模块成员函数的注释

2023-08-10 11:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/miniob?pullRequest=232) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/miniob?pullRequest=232) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/miniob?pullRequest=232) it.</sub>

2023-08-11 03:08 UTC, hnwyllmm commented on src/observer/storage/record/record_manager.cpp
> +         page_header_->record_capacity * page_header_->record_size, "Record overflow the page size");
ASSERT这里没有做判断

2023-08-11 03:11 UTC, hnwyllmm commented on src/observer/storage/record/record_manager.h
> +
这个宏定义仅在record_manager.cpp中使用，所以不应该放在这里。
另外，改成 const 或者 constexpr 更好

2023-08-11 03:11 UTC, hnwyllmm commented on src/observer/storage/record/record_manager.h
>    int32_t first_record_offset;  ///< 第一条记录的偏移量
可以解释下为啥要放在后面吗？

2023-08-11 03:13 UTC, JugendTraum commented on src/observer/storage/record/record_manager.h
>    int32_t first_record_offset;  ///< 第一条记录的偏移量
就是按初始化顺序排的

2023-08-11 03:14 UTC, hnwyllmm requested changes
改的很细致，非常感谢。有两个地方需要优化一下

2023-08-11 03:36 UTC, JugendTraum commented
改好了

2023-08-11 03:43 UTC, hnwyllmm approved these changes
LGTM

2023-08-11 05:43 UTC, merged