doxygen优化 首页说明单独写在一个md文档
oceanbase/miniob pull request #349
Opened 2024-03-06 17:35 UTC by DylanGuo916

### What problem were solved in this pull request?

Issue Number: close #252 

Problem:当前doxy文档中首页说明是放在main.cpp代码文件中的，这样写并不好，单独写在一个文本文档中更好一点。

### What is changed and how it works?
修改doxy配置文件 mainpage 单独写成一个 md 文件
### Other information

2024-03-06 17:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/miniob?pullRequest=349) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/miniob?pullRequest=349) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/miniob?pullRequest=349) it.</sub>

2024-03-07 05:19 UTC, hnwyllmm requested changes

2024-03-07 05:19 UTC, hnwyllmm commented on Doxyfile
> +USE_MDFILE_AS_MAINPAGE = src/observe/mainpage.md
Wrong path？

2024-03-07 07:11 UTC, DylanGuo916 commented on Doxyfile
> +USE_MDFILE_AS_MAINPAGE = src/observe/mainpage.md
yep

2024-03-07 08:12 UTC, DylanGuo916 commented on Doxyfile
> +USE_MDFILE_AS_MAINPAGE = src/observe/mainpage.md
> Wrong path？

have fixed

2024-03-07 09:39 UTC, hnwyllmm approved these changes

2024-03-07 09:40 UTC, merged