double write buffer
oceanbase/miniob pull request #367
Opened 2024-04-05 09:05 UTC by Wenbin1002

### What problem were solved in this pull request?

Issue Number: close #334 

Problem:

### What is changed and how it works?
实现double write buffer以解决页面的原子写入问题。
### Other information

2024-04-05 12:00 UTC, hnwyllmm requested changes
抱歉还没有review完，有一些review可以先修改一下。

2024-04-05 12:00 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  auto ret = dblwr_manager_.get_page(file_name_, page_num);
如果不能直接从代码中看出来变量的类型，不要用auto

2024-04-05 12:00 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  if (ret != std::nullopt) {
.cpp代码中已经用了 using namespace std; 所以不需要用std::了。如果这个文件没有加using ，可以加上来。

2024-04-05 12:00 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  } else {
对 buffer pool 的代码逻辑还是有调整的，可以把带double write buffer 的逻辑，加上相关的单元测试。

2024-04-05 12:00 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +    open_file(file_name.c_str(), *buf);
open_file可能会失败吧

2024-04-05 12:00 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +RC DoubleWriteBuffer::add_page(const std::string &file_name, Page page)
我记得page是一个非常大的对象，为什么直接用传值的方式传参呢？

2024-04-06 09:20 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  if (ret != std::nullopt) {
代码里面很多地方都用了std，需要我全改过来吗

2024-04-06 09:21 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +    return rc;
这里的日志我是在函数里面返回之前写的

2024-04-07 02:13 UTC, hnwyllmm requested changes

2024-04-07 02:13 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  if (lseek(disk_buffer->file_desc(), offset, SEEK_SET) == offset - 1) {
```cpp
DoubleWriteBuffer::write_page
    bufferPool.write_page

bufferPool.read_page
```

这两个调用栈，是冲突的，需要做并发控制。会出现两个线程操作同一个file_desc的情况。
从设计上来说，你不应该在一个类中，直接去操作另一个类的具体实现逻辑。

2024-04-07 02:13 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +    if (dblwr_page->get_file_name() == file_name && dblwr_page->get_page().page_num == page_num) {
使用 `file_name` + `page_num` 作为一个Key，Page作为value，组成一个map或unordered_map，效率会更高。

2024-04-07 02:37 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +    LOG_ERROR("Failed to add page %lld of %d due to failed to seek %s.", offset, file_desc_, strerror(errno));
这里我是直接复制的之前DiskBufferPool里面的代码，从之前调试的日志来看这个功能并没有问题，需要改成-1吗？

2024-04-07 02:38 UTC, Wenbin1002 commented on src/observer/storage/buffer/page.h
> +  std::string get_file_name() { return file_name_; }
这里是因为我后面需要使用bpm的哈希表来找DiskBufferPool，而哈希表的key是string，所以就直接返回的string

2024-04-07 02:44 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +    LOG_ERROR("Failed to add page %lld of %d due to failed to seek %s.", offset, file_desc_, strerror(errno));
那之前就有问题了。帮忙改成-1吧。

2024-04-07 02:45 UTC, hnwyllmm commented on src/observer/storage/buffer/page.h
> +  std::string get_file_name() { return file_name_; }
那在这里转换不合理，让disk buffer pool自己转换就行了。

2024-04-07 02:46 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  if (lseek(disk_buffer->file_desc(), offset, SEEK_SET) == offset - 1) {
这个地方能详细说一下吗，具体是哪一部分的代码

2024-04-07 02:49 UTC, Wenbin1002 commented on src/observer/storage/buffer/page.h
> +class DoubleWritePage
放在buffer pool.h 还是新建一个文件呢

2024-04-07 02:49 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  if (lseek(disk_buffer->file_desc(), offset, SEEK_SET) == offset - 1) {
看 DiskBufferPool::load_page:

<img width="1264" alt="image" src="https://github.com/oceanbase/miniob/assets/5187215/abe9a8bb-70ca-4b2b-b8c0-52016027920e">

2024-04-07 02:54 UTC, hnwyllmm commented on src/observer/storage/buffer/page.h
> +class DoubleWritePage
直接放在使用 DoubleWritePage  的类的上面吧。

2024-04-07 03:00 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  if (lseek(disk_buffer->file_desc(), offset, SEEK_SET) == offset - 1) {
不好意思我还是没明白是什么问题

2024-04-07 03:08 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  if (lseek(disk_buffer->file_desc(), offset, SEEK_SET) == offset - 1) {
一会在一些线程中执行 bufferPool::write，在另一些线程中执行 bufferPool::read，这两个动作都是同一个对象，但是并没有做并发控制。

2024-04-08 04:09 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.h
> +  DoubleWriteBuffer *dblwr_buffer_;
改成 `DoubleWriteBuffer *dblwr_buffer_ = nullptr;`
防止构造函数中忘记初始化dblwr_buffer_

2024-04-08 12:04 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +     * 如果bpm中没有对应的DiskBufferPool，就创建一个新的DiskBufferPool。
如果bpm中没有对应的DiskBufferPool
-->
这说明程序在退出？或者bmp在析构过程中，开始关闭diskBufferPool了。
在正常运行中，DiskBufferPool 打开之后，总会拿着第一个页面，程序在退出之前，也不会关闭DiskBufferPool。

如果是这样的话，在程序退出的时候，先想办法析构DoubleWriteBuffer然后再关闭DiskBufferPool是否可行？
或者关闭某个DiskBufferPool的时候，就需要释放DoubleWriteBuffer中相关的资源，毕竟DiskBufferPool已经关闭了，后面你又想办法给他打开了，还打开一个不一样的。

2024-04-08 12:32 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +     * 如果bpm中没有对应的DiskBufferPool，就创建一个新的DiskBufferPool。
![image](https://github.com/oceanbase/miniob/assets/85331908/04785d4b-788a-4602-bc55-0d9612e8d1e7)

在B+树的并发测试中，从我打的log来看，在测试过程中会很频繁的开关文件,bpm中没有DiskBufferPool并不代表程序已经结束，我对这点感到很奇怪。

2024-04-08 12:43 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +     * 如果bpm中没有对应的DiskBufferPool，就创建一个新的DiskBufferPool。
我看代码这个测试每个测试用例，预期只打开一个buffer pool文件。
每次打开和关闭文件，应该是一个测试用例结束了。
这个在正常业务逻辑中是不会出现的。
考虑一下bpm在关闭某个buffer pool时，如何处理DoubleWriteBuffer是不是把这个问题处理的更彻底，也会更清爽？
我看当前的代码中没有包含这些处理。

2024-04-08 13:41 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +     * 如果bpm中没有对应的DiskBufferPool，就创建一个新的DiskBufferPool。
因为我在注释里解释的原因，在write page时，要么必须保证flush page时buffer pool一定在bpm中，要么就用我现在采取的方案。事实上，我今天一下午都在尝试第一种方案。我在buffer pool关闭前调用dwb flush page，为了避免flush page时dwb还在add page，需要做并发控制。但是由于add page也会调用flush page函数，这个并发控制非常难处理。并且在buffer pool close_file()函数中还会调用bpm的close_file()函数，也就是说，在这两个函数之间有一个时刻，buffer pool的fd已经置为-1，而bpm的哈希表中还存在对应的buffer pool，这会导致文件写入失败。所以还需要保证这两个函数之间的原子性，而bpm的close_file函数最后会delete掉buffer pool，所以原子性也很难保证。这些问题非常难处理，我尝试了一下午之后在不大幅度修改原来代码的前提下没有什么很好的解决方案，所以才采用的现有方案。事实上现在的方案开销其实并不大，因为正常的业务中并不会频繁的开关文件。

2024-04-13 11:06 UTC, hnwyllmm requested changes

2024-04-13 11:06 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +    auto  dblwr_page = new DoubleWritePage();
DoubleWritePage的分配可以放到for循环外面，不用每次都重新分配。

2024-04-13 11:06 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  int ret = readn(file_desc_, &page_cnt, sizeof(int));
增加一个数据结构表示DoubleWriterBufferHeader，比使用简单的一个数字要更容易扩展。

2024-04-13 11:06 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +  int page_cnt = 0;
使用int32_t或者int64_t可以更明确的表示是多少位的数字，可以防止不同平台有不同的表现。

2024-04-13 11:06 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +      return RC::IOERR_READ;
假设最后一个页面写入一半时掉电了，你这里也会看到readn返回失败。

2024-04-13 12:21 UTC, Wenbin1002 commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +      return RC::IOERR_READ;
这里我修改了一下往dwb写入的逻辑，先写page，再写header。也就是说只有当页面写入成功后才会更新header里的page cnt。假设之前的最大page cnt是15，现在新写入后page cnt变为16，也就是多了一个页面。如果此时最后一个页面写入失败，那么header里面的page cnt 不会更新，还是15，在恢复时也就不会读取这个页面，这样还有没有问题？

2024-04-13 12:34 UTC, hnwyllmm commented on src/observer/storage/buffer/disk_buffer_pool.cpp
> +      return RC::IOERR_READ;
这样木问题。

2024-04-15 01:47 UTC, hnwyllmm approved these changes

2024-04-15 03:43 UTC, merged