support memory usage monitor
oceanbase/miniob pull request #391
Opened 2024-05-07 09:37 UTC by nautaa

### What problem were solved in this pull request?

Issue Number: close #385 

Problem:

### What is changed and how it works?

### Other information

2024-05-07 12:37 UTC, hnwyllmm requested changes

2024-05-07 12:37 UTC, hnwyllmm commented on deps/common/memtracer/memtracer.cpp
> +    fprintf(stderr, "Memory limit exceeded!\n");
看起来需要报出更详细的信息

2024-05-07 12:37 UTC, hnwyllmm commented on deps/common/memtracer/memtracer.cpp
> +      fprintf(
建议把输出信息封装为一个宏或一个函数，这样可以很方便的增加前缀、后缀等信息

2024-05-07 12:37 UTC, hnwyllmm commented on deps/common/memtracer/memtracer.h
> +/* Copyright (c) 2021 OceanBase and/or its affiliates. All rights reserved.
应该有一个对“用户”可用的头文件和一些函数，所有其它符号都应该隐藏起来。

2024-05-07 12:37 UTC, hnwyllmm commented on deps/common/memtracer/memtracer.h
> +#define likely(x) __builtin_expect(!!(x), 1)
如果memtracer.h是对用户可用的，那么不应该在这里定义likely这个宏，用户极有可能也会定义这样的一个宏

2024-05-07 12:37 UTC, hnwyllmm commented on deps/common/memtracer/memtracer.h
> +  pthread_once_t      init_hook_funcs_once_;
可以用C++的 call_once

2024-05-07 12:37 UTC, hnwyllmm commented on deps/common/memtracer/memtracer.cpp
> +  MT.init_hook_funcs();
在当前对象的函数中又去调用静态实例对象，看起来很奇怪。

2024-05-08 11:39 UTC, nautaa commented on deps/common/memtracer/allocator.cpp
> +void *operator new(std::size_t size) { return malloc(size); }
可能会有问题，之前和asan一起调试的时候遇到过。

2024-05-08 11:40 UTC, nautaa commented on deps/common/memtracer/allocator.cpp
> +{
取决于strdup 的实现，不一定会走malloc，调试的时候遇到过问题。参考 mimalloc的实现。

2024-05-08 11:42 UTC, nautaa commented on deps/common/memtracer/memtracer.cpp
> +  MT.init_hook_funcs();
这里是一个特殊的函数，用于在动态库加载时做一些初始化。

2024-05-13 11:36 UTC, hnwyllmm requested changes

2024-05-13 11:36 UTC, hnwyllmm commented on unittest/CMakeLists.txt
> +set(MEMTRACER_PATH "${CMAKE_BINARY_DIR}/lib/libmemtracer.so")
这个看起来没有使用。

2024-05-13 11:36 UTC, hnwyllmm commented on deps/memtracer/allocator.h
> +#include <sys/mman.h>  // mmap/munmap
可以把系统头文件放在最前面。

2024-05-13 11:36 UTC, hnwyllmm commented on deps/memtracer/allocator.h
> +extern "C" mt_visible void *malloc(size_t size);
malloc这些函数不需要时 visible 模式吧？

2024-05-13 11:36 UTC, hnwyllmm commented on deps/memtracer/mt_info.h
> +#include "memtracer.h"
mt_info 是对外暴露的文件，是否可以不再引入其它文件？

2024-05-13 12:48 UTC, nautaa commented on deps/memtracer/allocator.h
> +extern "C" mt_visible void *malloc(size_t size);
经测试，不指定的话可能无法覆盖原函数。参考 mimalloc 也是显式指定 visibility 的 。

2024-05-13 12:57 UTC, hnwyllmm approved these changes

2024-05-14 03:03 UTC, merged