fix typo in lex_sql.l
oceanbase/miniob pull request #470
Opened 2024-10-24 14:15 UTC by ZJY0516

### What problem were solved in this pull request?

在`lex_sql.l`中，`WHITE_SPACE`被写成了`WHITE_SAPCE`

2024-10-24 14:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/miniob?pullRequest=470) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/miniob?pullRequest=470) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/miniob?pullRequest=470) it.</sub>

2024-10-25 02:06 UTC, nautaa approved these changes
LGTM

2024-10-25 02:10 UTC, hnwyllmm requested changes
Thanks for your pull request, but you should execute `gen_parser.sh` to generate new cpp code files.

2024-10-25 02:50 UTC, hnwyllmm approved these changes
LGTM

2024-10-25 03:38 UTC, merged