增加线程线程名称，top时可以看到线程名称，便于调试。
oceanbase/miniob pull request #79
Opened 2022-09-15 13:39 UTC by FrankXMX

![image](https://user-images.githubusercontent.com/31796712/190418759-ba8e858f-3ba2-465f-99a9-0a2b51dcc9c8.png)

2022-09-15 13:49 UTC, FrankXMX commented
PTAL

2022-09-16 02:34 UTC, hnwyllmm requested changes
这个修改非常有意思，很感谢

2022-09-16 02:34 UTC, hnwyllmm commented on deps/common/seda/thread_pool.cpp
> +    char tmp[32] = {};
The thread name is a
       meaningful C language string, whose length is restricted to 16
       characters, including the terminating null byte ('\0'). 

按照手册中的描述，这里的buffer不需要设置的太长

2022-09-16 02:34 UTC, hnwyllmm commented on deps/common/seda/thread_pool.cpp
> +    sprintf(tmp,"%s%u",name_.c_str(), i);
不要使用sprintf，要使用snprintf

2022-09-16 02:34 UTC, hnwyllmm commented on deps/common/seda/timer_stage.cpp
> +  pthread_setname_np(timer_thread_id_, "TimerStage");
如果线程创建失败，这里也不需要修改线程的名字了

2022-09-16 03:50 UTC, hnwyllmm approved these changes
LGTM

2022-09-16 03:51 UTC, merged

2022-09-17 03:12 UTC, Joenhle commented
<img width="912" alt="image" src="https://user-images.githubusercontent.com/56585772/190838415-8a752ef5-ebcb-455a-ad1a-6ba978407032.png">
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/56585772/190838439-d1156cd1-1cec-4cc8-8cae-e91ff48ff7ca.png">
请问这里是有bug吗？我是Mac环境，拉取main分支最新的编译出错了。

2022-09-19 02:01 UTC, hnwyllmm commented
Mac上的接口与Linux上确实不同

2022-09-19 03:35 UTC, Frank-gh requested changes
fix in #80