fix issue 'client_performance_test' failed
oceanbase/miniob pull request #80
Opened 2022-09-16 08:42 UTC by FrankXMX

![image](https://user-images.githubusercontent.com/31796712/190596011-61edfc55-53c6-4044-ba82-69e0bb823980.png)

2022-09-16 08:42 UTC, FrankXMX commented
/PTAL

2022-09-19 05:00 UTC, hnwyllmm requested changes
如果不带上pthread_setname_np的修复，是没有问题的

2022-09-19 05:00 UTC, hnwyllmm commented on deps/common/seda/thread_pool.cpp
> +#ifdef __GLIBC__ // pthread_setname_np not work on MAC
pthread_setname_np在Mac上的原型是
```
void
     pthread_setname_np(const char *name);
```
并不是没有这个函数

2022-09-19 06:21 UTC, FrankXMX commented on deps/common/seda/thread_pool.cpp
> +#ifdef __GLIBC__ // pthread_setname_np not work on MAC
看原型，Mac上的pthread_setname_np应该是不允许在其他线程中设置线程名称的，因此在这里设置线程名是不合理的。后续考虑一下如何修改这个功能，这里用先__GLIBC__ 屏蔽掉在Mac上显示线程名的功能。

2022-09-20 05:47 UTC, hnwyllmm commented on deps/common/seda/thread_pool.cpp
> +#ifdef __GLIBC__ // pthread_setname_np not work on MAC
这个修改本身并不复杂，不需要临时解决方案。解决client连接的问题即可，另外一个问题可以新开一个PR。

2022-09-20 06:41 UTC, FrankXMX commented
我这边没有Mac环境，代码没有在Mac上进行验证。

2022-09-20 09:39 UTC, hnwyllmm requested changes

2022-09-20 09:39 UTC, hnwyllmm commented on deps/common/seda/thread_pool.cpp
> +  pthread_setname_np(threadid, pool->get_name().c_str());
gettid 返回的thread id与 pthread_self返回的thread id是不一样的，应该使用pthread那一套

2022-09-20 10:31 UTC, FrankXMX commented on deps/common/seda/thread_pool.cpp
> +  pthread_setname_np(threadid, pool->get_name().c_str());
gettid 获取的是内核中线程ID，同top命令显示的也是内核的线程ID，所以这块应该是使用gettid，从而达到在top中显示线程名称的目的，pthread_self应该是用户态的线程ID。实测top命令可以识别并显示正确的线程名称。

2022-09-20 12:37 UTC, hnwyllmm commented on deps/common/seda/thread_pool.cpp
> +  pthread_setname_np(threadid, pool->get_name().c_str());
之前你写的代码是pthread_create 的返回值，作为thread id，那个值就是pthread_self的返回值

```c
int pthread_create(pthread_t *thread, const pthread_attr_t *attr,
                          void *(*start_routine) (void *), void *arg);
pthread_t pthread_self(void);
pid_t gettid(void);
```

通过三个函数的原型也可以看出来的

2022-09-21 01:21 UTC, FrankXMX commented on deps/common/seda/thread_pool.cpp
> +  pthread_setname_np(threadid, pool->get_name().c_str());
测了一下，pthread_self和gettid两个方法的返回值都能最为pthread_setname_np的第一个参数，且能设置成功。我觉得您说的有道理，应该与TimerStage的设置方法保持一致。后续再去研究一下为什么两种方式的效果会相同。

2022-09-21 01:50 UTC, merged