support build with address sanitizer and fix some memory leaks
oceanbase/miniob pull request #86
Opened 2022-09-22 15:21 UTC by atoomix

2022-09-22 15:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/miniob?pullRequest=86) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/miniob?pullRequest=86) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/miniob?pullRequest=86) it.</sub>

2022-09-22 15:22 UTC, atoomix commented
related issue #37

2022-09-23 05:12 UTC, hnwyllmm requested changes

2022-09-23 05:12 UTC, hnwyllmm commented on src/observer/event/sql_event.cpp
> +#include <cstddef>
C或者C++的标准头文件放在最前面会更好

2022-09-23 15:03 UTC, hnwyllmm approved these changes

2022-09-23 15:03 UTC, merged